In [ ]:
#         Agenda
#creating array from Ethiopian cities to port dataframe
#create and select arrays
#operations on arrays
#aggregation on arrays
#nut butter practical example
#sorting arrays
#turn images into numpy arrays

In [2]:
#import np and pd liberary
import numpy as np
import pandas as pd

In [23]:
sample=pd.read_csv("sample.csv")
sample["massawa_road_distance"]=sample["massawa_road_distance"].astype(float)
sample["massawa_road_duration"]=sample["massawa_road_duration"].astype(float)
sample

Unnamed: 0.1  Unnamed: 0  city_name  \
0            198         198     Gidole   
1             34          34      Mendi   
2            114         114      Danan   
3             42          42      Nedjo   
4            240         240  Bahir Dar   
5            190         190      Turmi   
6             47          47       Robe   
7            267         267   Meshenti   
8            246         246   Chew Ber   
9            151         151     Mekele   
10           214         214     Zefine   

                                               region          zone  \
0   Southern Nations, Nationalities, and People's ...       Dirashe   
1                                              Oromia  West Wellega   
2                                              Somali          Gode   
3                                              Oromia  West Wellega   
4                                              Amhara    West Gojam   
5   Southern Nations, Nationalities, and People's ...           Omo   
6                                              Oromia          Bale   
7                                              Amhara    West Gojam   
8                                              Amhara  North Gondar   
9                                              Tigray  South Tigray   
10  Southern Nations, Nationalities, and People's ...     Gamo Gofa   

    massawa_road_distance  massawa_road_duration   latitude  longitude  
0                  1060.0                91937.0   5.649749  37.369368  
1                   982.0                98728.0   9.797018  35.099369  
2                  1212.0               102303.0   6.513115  43.495770  
3                   938.0                94483.0   9.502294  35.502838  
4                   578.0                58074.0  11.574209  37.361353  
5                  1172.0               105061.0   4.964093  36.487824  
6                   953.0                81860.0   7.119903  40.006895  
7                   588.0                58685.0  11.474502  37.283833  
8                   368.0                35268.0  13.401127  38.001626  
9                   248.0                21492.0  13.493550  39.465738  
10                  997.0                87629.0   6.471833  37.638279

In [24]:
sample.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Unnamed: 0.1           11 non-null     int64  
 1   Unnamed: 0             11 non-null     int64  
 2   city_name              11 non-null     object 
 3   region                 11 non-null     object 
 4   zone                   11 non-null     object 
 5   massawa_road_distance  11 non-null     float64
 6   massawa_road_duration  11 non-null     float64
 7   latitude               11 non-null     float64
 8   longitude              11 non-null     float64
dtypes: float64(4), int64(2), object(3)
memory usage: 920.0+ bytes


In [25]:
sample_array = sample[["massawa_road_distance","massawa_road_duration","latitude","longitude"]].to_numpy()
sample_array

array([[1.06000000e+03, 9.19370000e+04, 5.64974930e+00, 3.73693679e+01],
       [9.82000000e+02, 9.87280000e+04, 9.79701750e+00, 3.50993687e+01],
       [1.21200000e+03, 1.02303000e+05, 6.51311450e+00, 4.34957704e+01],
       [9.38000000e+02, 9.44830000e+04, 9.50229360e+00, 3.55028379e+01],
       [5.78000000e+02, 5.80740000e+04, 1.15742086e+01, 3.73613533e+01],
       [1.17200000e+03, 1.05061000e+05, 4.96409330e+00, 3.64878241e+01],
       [9.53000000e+02, 8.18600000e+04, 7.11990310e+00, 4.00068953e+01],
       [5.88000000e+02, 5.86850000e+04, 1.14745024e+01, 3.72838328e+01],
       [3.68000000e+02, 3.52680000e+04, 1.34011273e+01, 3.80016255e+01],
       [2.48000000e+02, 2.14920000e+04, 1.34935504e+01, 3.94657380e+01],
       [9.97000000e+02, 8.76290000e+04, 6.47183270e+00, 3.76382794e+01]])

# creating and selecting arrays

In [4]:
#create two dimensional array
a=np.array([[1,2,3],[3,4,5]])
a


array([[1, 2, 3],
       [3, 4, 5]])

In [5]:
# the following are the same
a[0]#select specific row 
a[0][:]

array([1, 2, 3])

In [14]:
# a[:,2]#select specific columun
a[:,2]

array([3, 5])

In [10]:
#create ones with dimensiona of 2 by 3
ones=np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
#create full array filled with 5
full=np.full((2,3),5)
full

array([[5, 5, 5],
       [5, 5, 5]])

In [3]:
#why rand is error  "tuple' object cannot be interpreted as an integer"
np.random.random((3,5))

array([[0.58337479, 0.52152185, 0.32150371, 0.17746699, 0.16035779],
       [0.19176878, 0.06715663, 0.62272998, 0.64920007, 0.71407182],
       [0.31676192, 0.61415752, 0.12902808, 0.46542399, 0.69996804]])

In [15]:
d=np.identity(3)#identity matrices

In [16]:
np.linalg.det(d)

1.0

In [20]:
np.array([[2,3,4],[5,6,7]])#why use two slashes

array([[2, 3, 4],
       [5, 6, 7]])

In [21]:
#np vertical and horizontal stack

In [27]:
np.random.seed(seed=10)
np.random.random((3,5))

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701],
       [0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981],
       [0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096]])

In [23]:
#refers index to be created
np.random.rand(3,5)

array([[0.61252607, 0.72175532, 0.29187607, 0.91777412, 0.71457578],
       [0.54254437, 0.14217005, 0.37334076, 0.67413362, 0.44183317],
       [0.43401399, 0.61776698, 0.51313824, 0.65039718, 0.60103895]])

In [3]:
#three dimension array
a3=np.random.rand(2,3,4)
a3

array([[[0.09481038, 0.4271167 , 0.6988716 , 0.1863323 ],
        [0.69615718, 0.57125658, 0.21581541, 0.94422068],
        [0.56059775, 0.26348474, 0.11569995, 0.37135829]],

       [[0.31315586, 0.22185316, 0.19596822, 0.66648253],
        [0.89094498, 0.76024317, 0.5850182 , 0.16361217],
        [0.0832811 , 0.58763904, 0.67906297, 0.15597267]]])

In [4]:
a3[:1]

array([[[0.09481038, 0.4271167 , 0.6988716 , 0.1863323 ],
        [0.69615718, 0.57125658, 0.21581541, 0.94422068],
        [0.56059775, 0.26348474, 0.11569995, 0.37135829]]])

In [21]:
#selecting a specfic element
a3[0][2][0]

0.47504484950272197

# operations on arrays using numpy

In [7]:
#craeting one,two dimendsion array
a0=np.array([2,4,5])
a1=np.array([2,3,6])
a2=np.array([[1,4,5],[3,2,4]])
a3=np.random.rand(2,3,4)
a0,a1,a2,a3

(array([2, 4, 5]),
 array([2, 3, 6]),
 array([[1, 4, 5],
        [3, 2, 4]]),
 array([[[0.6409379 , 0.64896061, 0.24693335, 0.14852702],
         [0.29994036, 0.14759699, 0.73597061, 0.9617051 ],
         [0.18122573, 0.71732377, 0.05715204, 0.75239894]],
 
        [[0.34485806, 0.61660528, 0.70560297, 0.78099139],
         [0.32884753, 0.11851454, 0.95742867, 0.8386706 ],
         [0.07267655, 0.43609267, 0.50085152, 0.21943497]]]))

In [29]:
#product of one dimensions
a0*a1

array([ 4, 12, 30])

In [48]:
#product of one with two dimensions
a0*a2

array([[ 2, 16, 25],
       [ 6,  8, 20]])

In [30]:
#logarithmic functions
np.log(a0)

array([0.69314718, 1.38629436, 1.60943791])

In [54]:
#squre of a0
a0 ** 2

array([ 4, 16, 25], dtype=int32)

In [56]:
#the same as a0 ** 2
np.square(a0)

array([ 4, 16, 25], dtype=int32)

In [58]:
#squering two dimndsion
np.square(a2)

array([[ 1, 16, 25],
       [ 9,  4, 16]], dtype=int32)

In [59]:
#logarithm of two dimension
np.log(a2)

array([[0.        , 1.38629436, 1.60943791],
       [1.09861229, 0.69314718, 1.38629436]])

In [60]:
#division of two dimendsion by one dimension
a2/a0

array([[0.5, 1. , 1. ],
       [1.5, 0.5, 0.8]])

In [62]:
#division by itself
a2/a2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [64]:
#product of one and two dimension
a2*a0

array([[ 2, 16, 25],
       [ 6,  8, 20]])

In [65]:
#product by itself
a2*a2

array([[ 1, 16, 25],
       [ 9,  4, 16]])

In [66]:
#division
a2%2

array([[1, 0, 1],
       [1, 0, 0]], dtype=int32)

In [68]:
#euler constant the power of array
np.exp(a2)

array([[  2.71828183,  54.59815003, 148.4131591 ],
       [ 20.08553692,   7.3890561 ,  54.59815003]])

In [70]:
#e the power of number
np.exp(a0)

array([  7.3890561 ,  54.59815003, 148.4131591 ])

# agggregation on arrays using numpy

In [8]:
a0,a1,a2,a3


(array([2, 4, 5]),
 array([2, 3, 6]),
 array([[1, 4, 5],
        [3, 2, 4]]),
 array([[[0.6409379 , 0.64896061, 0.24693335, 0.14852702],
         [0.29994036, 0.14759699, 0.73597061, 0.9617051 ],
         [0.18122573, 0.71732377, 0.05715204, 0.75239894]],
 
        [[0.34485806, 0.61660528, 0.70560297, 0.78099139],
         [0.32884753, 0.11851454, 0.95742867, 0.8386706 ],
         [0.07267655, 0.43609267, 0.50085152, 0.21943497]]]))

In [10]:
a0.size,a1.size,a2.size,a3.size

(3, 3, 6, 24)

In [44]:
a0.shape,a1.shape,a2.shape,a3.shape

((3,), (3,), (2, 3), (2, 3, 4))

In [78]:
#same of all array elemnts
np.sum(a2)

19

In [90]:
#creating array of strings

In [39]:
#variance
np.var(a2[0])

2.8888888888888893

In [40]:
#standard deviation
np.std(a2)

1.3437096247164249

In [103]:
np.mean(a1)

3.75

In [104]:
np.mean(a2)

3.1666666666666665

In [41]:
a2.reshape(3,2,1)

array([[[1],
        [4]],

       [[5],
        [3]],

       [[2],
        [4]]])

In [42]:
a2.transpose()

array([[1, 3],
       [4, 2],
       [5, 4]])

In [137]:
a3.T

array([[6, 3],
       [0, 0],
       [4, 1]])

In [68]:
a1.shape,a2.shape
a4=a1.reshape(1,3)
a5=a2.T
a5.shape

(3, 2)

In [71]:
a4,a5

(array([[2, 3, 6]]),
 array([[1, 3],
        [4, 2],
        [5, 4]]))

In [70]:
np.dot(a4,a5)

[[44 36]]


# nut butter practical example

In [78]:
#creating sales amount array 
salesAmount=np.random.randint(20,size=(5,3))
salesAmount

array([[10, 15,  9],
       [ 5, 14,  3],
       [ 1,  8,  4],
       [ 2,  6,  2],
       [ 4, 19,  8]])

In [79]:
#creating weekly sales dataframe
weeklySales=pd.DataFrame(salesAmount,index=["mon","tue","wed","thrsday","friday"],
                        columns=["almond buttter","peanut Butter","cashew Butter"])
weeklySales

almond buttter  peanut Butter  cashew Butter
mon                  10             15              9
tue                   5             14              3
wed                   1              8              4
thrsday               2              6              2
friday                4             19              8

In [80]:
#create prices array
prices=pd.array([10,8,6])

In [81]:
prices

<IntegerArray>
[10, 8, 6]
Length: 3, dtype: Int64

In [85]:
#create price dataframe from prices array
price=pd.DataFrame(prices.reshape(1,3),index=["prices"],
                   columns=["almond buttter","peanut Butter","cashew Butter"])


In [86]:
price.shape

(1, 3)

In [92]:

# salesAmount
total_sales=price.dot(weeklySales.T)
total_sales
# prices
weeklySales["total($)"]=total_sales.T

In [93]:
# prices=prices.reshape(3,1)
weeklySales

almond buttter  peanut Butter  cashew Butter total($)
mon                  10             15              9      274
tue                   5             14              3      180
wed                   1              8              4       98
thrsday               2              6              2       80
friday                4             19              8      240

# sorting arrays

In [72]:
to_sort=np.random.randint(10,size=(3,4))
to_sort


array([[8, 2, 0, 6],
       [2, 8, 1, 4],
       [2, 5, 7, 6]])

In [73]:
np.sort(to_sort)#arg sort returns index

array([[0, 2, 6, 8],
       [1, 2, 4, 8],
       [2, 5, 6, 7]])

In [76]:
np.min(to_sort)

0

In [77]:
np.max(to_sort)

8

In [59]:
np.argmin(to_sort)

0

In [74]:
np.argmax(to_sort)

0

# turn  images into numpy arrays

In [78]:
from  matplotlib.image import imread
#<img src='artifitial.jpg' />

<img src='artifitial.jpg' />

<img src=""/>

In [81]:
array=imread('artifitial.jpg')
array

array([[[ 0,  0,  5],
        [ 0,  2,  9],
        [ 0,  1,  8],
        ...,
        [ 0,  0, 11],
        [ 1,  1, 13],
        [ 1,  1, 13]],

       [[ 0,  1,  6],
        [ 0,  2,  9],
        [ 0,  0,  7],
        ...,
        [ 2,  2, 14],
        [ 0,  0, 11],
        [ 0,  0, 11]],

       [[ 0,  3,  8],
        [ 0,  2,  9],
        [ 0,  0,  7],
        ...,
        [ 3,  5, 18],
        [ 0,  0, 13],
        [ 0,  0, 13]],

       ...,

       [[ 0,  0, 12],
        [ 0,  6, 19],
        [ 0,  8, 23],
        ...,
        [ 4, 20, 54],
        [ 0, 14, 47],
        [ 6, 21, 52]],

       [[ 0,  3, 15],
        [ 3, 11, 24],
        [ 3, 12, 27],
        ...,
        [11, 27, 61],
        [ 1, 16, 49],
        [10, 25, 56]],

       [[ 6, 12, 24],
        [ 5, 13, 26],
        [ 1, 10, 25],
        ...,
        [18, 34, 68],
        [18, 33, 66],
        [29, 44, 75]]], dtype=uint8)